/**
 * This file was generated by the Jeddict
 */
package com.udea.webconcesionaire.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

/**
 * @author marit
 */
@Entity(name = "Vehicle") 
public class Vehicle {

    @Column(unique = true, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long vehicle_id;

    @Basic
    private String make;

    @Basic
    private String model;

    @Basic
    private String year_vehicle;

    @Basic
    private String color;

    @Basic
    private String mileage;

    @Basic
    private String description;

    @Basic
    private double price;

    @OneToMany(mappedBy = "vehicle")
    private List<Photo> photos;

    @ManyToMany
    private List<Sale> sales;

    public Vehicle() {
    }

    public Vehicle(Long vehicle_id, String make, String model, String year_vehicle, String color, String mileage, String description, double price, List<Photo> photos, List<Sale> sales) {
        this.vehicle_id = vehicle_id;
        this.make = make;
        this.model = model;
        this.year_vehicle = year_vehicle;
        this.color = color;
        this.mileage = mileage;
        this.description = description;
        this.price = price;
        this.photos = photos;
        this.sales = sales;
    }

    public Long getVehicle_id() {
        return this.vehicle_id;
    }

    public void setVehicle_id(Long vehicle_id) {
        this.vehicle_id = vehicle_id;
    }

    public String getMake() {
        return this.make;
    }

    public void setMake(String make) {
        this.make = make;
    }

    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getYear_vehicle() {
        return this.year_vehicle;
    }

    public void setYear_vehicle(String year_vehicle) {
        this.year_vehicle = year_vehicle;
    }

    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getMileage() {
        return this.mileage;
    }

    public void setMileage(String mileage) {
        this.mileage = mileage;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public List<Photo> getPhotos() {
        if (photos == null) {
            photos = new ArrayList<>();
        }
        return this.photos;
    }

    public void setPhotos(List<Photo> photos) {
        this.photos = photos;
    }

    public void addPhoto(Photo photo) {
        getPhotos().add(photo);
        photo.setVehicle(this);
    }

    public void removePhoto(Photo photo) {
        getPhotos().remove(photo);
        photo.setVehicle(null);
    }

    public List<Sale> getSales() {
        if (sales == null) {
            sales = new ArrayList<>();
        }
        return this.sales;
    }

    public void setSales(List<Sale> sales) {
        this.sales = sales;
    }

    public void addSale(Sale sale) {
        getSales().add(sale);
        sale.getVehicles().add(this);
    }

    public void removeSale(Sale sale) {
        getSales().remove(sale);
        sale.getVehicles().remove(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final Vehicle other = (Vehicle) obj;
        if (!java.util.Objects.equals(this.getVehicle_id(), other.getVehicle_id())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getVehicle_id());
        return hash;
    }

    @Override
    public String toString() {
        return "Vehicle{" + " vehicle_id=" + vehicle_id + ", make=" + make + ", model=" + model + ", year_vehicle=" + year_vehicle + ", color=" + color + ", mileage=" + mileage + ", description=" + description + ", price=" + price + ", photos=" + photos + ", sales=" + sales + '}';
    }

}